### ISSUE TITLE
Add pre-commit hook to run mix test on localhost?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#20]
I've just pushed a commit on my branch thinking the tests were passing (_I didn't check_)
and then watched them fail on Travis-CI 🤦‍♂ 

Should we be using https://github.com/dwyl/elixir-pre-commit to prevent failing commits? 👮 
Or is one of the benefits of CI that it offloads running tests to [someone _else's_ computer](https://www.google.com/search?q=there+is+no+cloud+meme&tbm=isch)? 💻 

@SimonLab how do you feel about pre-commit hooks that run tests on `localhost` ***`before`*** pushing to GitHub? Is it better to know _sooner_ that tests are failing or to be informed by CI? 🤔

**Comment by SimonLab** [comment]
I think I prefer having the tests checked first on localhost just to make sure that everything is working correctly but also if we let CI check first we might assume that everything is fine and only notice the error hours later. This often requires more time to get back to the code we were working and to fix any bugs.

However when the build time is long I'm using the CI (and keep an eye on it) to be able to continue to work on other things.

So yes I think for the project we could try to use pre-commits. I would also like to add [Credo](https://github.com/rrrene/credo) and run `mix format` on pre-commit.

**Comment by nelsonic** [comment]
This will probably end up saving us time in the medium/long run, so we might as well add it soon ... 💭

**Comment by nelsonic** [comment]
Working:
![image](https://user-images.githubusercontent.com/194400/94908968-5c015d00-049a-11eb-9522-8638139fc570.png)
