### ISSUE TITLE
Add excoveralls + Codecov to track test coverage

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#21]
As a developer wanting to confirm that we don't have untested/unused code,
I want to track coverage for the project so that we know if things are on track.

+ [x] create `coveralls.json` file - https://github.com/dwyl/phoenix-chat-example/blob/master/coveralls.json
+ [x] add `:excoveralls` to `dependencies`  - https://github.com/dwyl/phoenix-chat-example/blob/89d5d1127bafdcb9493c5dab060c291aa296f5e2/mix.exs#L58-L59
+ [x] `cover` command in `mix.exs` - https://github.com/dwyl/phoenix-chat-example/blob/89d5d1127bafdcb9493c5dab060c291aa296f5e2/mix.exs#L73-L81
+ [x] Add codecov script to `.travis.yml` - https://github.com/dwyl/phoenix-chat-example/blob/89d5d1127bafdcb9493c5dab060c291aa296f5e2/.travis.yml#L10-L13
+ [x] Add codecov badge to `README.md` 

This is a nice-to-have technical feature that only _indirectly_ affects "users" further down the line.
We should work on this in our "down time" _after_ the [sprint](https://github.com/dwyl/app/milestone/2) is complete  👍

**Comment by SimonLab** [comment]
done with #26 but keeping open as it looks like the coverage report hasn't been generated by codecov yet

**Comment by nelsonic** [comment]
@SimonLab the reason the report is not being generated is that we aren't invoking `mix coveralls.json` in the `.travis.yml` file ... see: https://github.com/dwyl/app-mvp-phoenix/pull/28

**Comment by nelsonic** [comment]
https://travis-ci.com/dwyl/app-mvp-phoenix/builds/139021125#L490
![image](https://user-images.githubusercontent.com/194400/69985457-1bac1800-1533-11ea-9dca-786b4a75e071.png)

**Comment by nelsonic** [comment]
Done: [![codecov.io](https://img.shields.io/codecov/c/github/dwyl/app-mvp-phoenix/master.svg?style=flat-square)](http://codecov.io/github/dwyl/app-mvp-phoenix?branch=master)
