### ISSUE TITLE
Do not display Google Login button when already logged in

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#34]
At the moment when visiting the `/` endpoint the Google signin button is always displayed even when the user is already loggedin:

![image](https://user-images.githubusercontent.com/6057298/70141581-4317f780-168f-11ea-98f9-e8da165e0743.png)

- [x] Check if user is loggedin
- [x] Redirect to user information page when loggedin
- [x] Display Google signin if not loggedin

This require the index view of the goog_auth_controller to be on its self `user information` controller to be able to redirect the user if already loggedin

- [x] Create info endpoint which display basic info of the loggedin user

**Comment by nelsonic** [comment]
Works as expected. 👍
