### ISSUE TITLE
Seeds are not idempotent (duplicate status created)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#39]
Because there is no code to check if the `status` already exists in `seeds.exs`:
https://github.com/dwyl/app-mvp-phoenix/blob/4c96ce38ea935149257c879686abfb522b3e283b/priv/repo/seeds.exs#L1-L2

It's possible to have duplicate statusus:
![image](https://user-images.githubusercontent.com/194400/70189062-28bf3780-16ea-11ea-859c-4742555f5010.png)

When I run `MIX_ENV=test mix ecto.reset` 
followed by `mix test` on my `localhost` I see this error:
![image](https://user-images.githubusercontent.com/194400/70188949-f4e41200-16e9-11ea-9cde-80bf255dfb5b.png)
Indicating that there are _duplicate_ records for status being created.

@SimonLab can you help investigate tomorrow morning? (_Thanks!_) ✨

**Comment by SimonLab** [comment]
I had the same error with reset: `reset` is going to drop the database, create it again, run the migration then **run the seed**. Then when the `test` command is run the seed file is run again as we have now the alias define as : `test: ["ecto.create --quiet", "ecto.migrate", "run priv/repo/seeds.exs", "test"]` So the seed file is run twice.

If instead you use `drop`: `MIX_ENV=test mix ecto.drop` then `mix test` the seed file should be ok and run only once.
I know it's not perfect and I need to find a better way to run the seed on test

**Comment by nelsonic** [comment]
Fixed by updating the aliases. (_thanks @SimonLab_)

https://github.com/dwyl/app-mvp-phoenix/blob/015f3738649eed9f993409599ce3335586d98fe6/mix.exs#L77-L85
