### ISSUE TITLE
Heroku deployement error with Erlang 22

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#44]
![image](https://user-images.githubusercontent.com/6057298/70637596-644c8b00-1c2f-11ea-86e6-37b612f80c46.png)

I think the Erlang version is not found and can't be installed.

**Comment by nelsonic** [comment]
@SimonLab Erlang 22 working in [github.com/dwyl/elixir-auth-google-demo > `elixir_buildpack.config`](https://github.com/dwyl/elixir-auth-google-demo/blob/master/elixir_buildpack.config)
