### ISSUE TITLE
Error when Using Google Singin

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#48]
an `Internal Server Error` is displayed when attempting to login with Google.
We don't have much more information on the server log on Heroku.
My first thought is to check that the callback url might not be defined to `https://dwylapp.herokuapp.com/auth/google/callback` on the Google application

@nelsonic when you have time can you check this value on the Application? Thanks

**Comment by SimonLab** [comment]
Another possible error, is that the database needs to be reset on Heroku as we have changed some previous run migrations files

**Comment by nelsonic** [comment]
Investigating ... 🕵

**Comment by nelsonic** [comment]
![heroku-database-reset](https://user-images.githubusercontent.com/194400/70644006-01acbc80-1c3a-11ea-99c4-1b158d9b0912.png)

Re-deploying `master` ... ⏳ 

![image](https://user-images.githubusercontent.com/194400/70644033-1426f600-1c3a-11ea-8c9f-6eb6ab9fe4c9.png)

Stilling getting the internal server error:
![image](https://user-images.githubusercontent.com/194400/70644069-2d2fa700-1c3a-11ea-8b34-dd8cff6c3f43.png)

**Comment by nelsonic** [comment]
Worked after you ran the `seeds` script ...
![image](https://user-images.githubusercontent.com/194400/70644177-67994400-1c3a-11ea-8223-1c98c9f36293.png)

**Comment by SimonLab** [comment]
Confirmed it's working for me too. So resetting the database resolve this issue

steps with heroku cli
```
heroku pg:info
heroku pg:reset DATABASE_NAME
heroku run MIX_ENV=prod mix ecto.migrate
heroku run MIX_ENV=prod mix run priv/repo/seeds.exs
heroku restart
```

**Comment by nelsonic** [comment]
@SimonLab thanks for posting the Heroku CLI commands. 👍 
Please feel free to close the issue if you feel it's working to your satisfaction. 😉
