### ISSUE TITLE
Configure CORS for api endpoints

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#56]
While testing the Elm PWA which send a post request to the Phoenix api a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error appeared:
![image](https://user-images.githubusercontent.com/6057298/70905675-5ebebe80-1ffc-11ea-9660-eaf48db8f486.png)

This means that at the moment the server doesn't allow request which are not from it's own origin (ie coming from a page rendered previously by the server itself). Because I'm testing the Elm PWA on `localhost:8000` the origin of the request is different to https://dwylapp.herokuapp.com which produce the error.

The following elixir package can be used to configure what origns are allowed to send request to your server
- https://github.com/mschae/cors_plug
- https://github.com/whatyouhide/corsica

I'm going to try cors_plug to allow temporarily request from localhost while testing. Once the Elm application is hosted we can update the origin to only allow requests from this server.

**Comment by SimonLab** [comment]
Read:
https://medium.com/@yagoazedias/how-to-configure-cors-in-your-phoenix-application-5ef0234bc25f

The article explains how to use `option` for routes when using cors_plug

**Comment by nelsonic** [comment]
Merged in #57
