### ISSUE TITLE
Cookie SameSite Warnings

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#70]
Got this warning in the Firefox Developer Console:
```
Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “_app_key” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite new
Cookie “__cfduid” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 2 android-icon-192x192.png
Cookie “__cfduid” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 2 favicon-16x16.png
```

![image](https://user-images.githubusercontent.com/194400/94998291-aec93a80-05a8-11eb-9dbe-16b4c1d24494.png)

The `_app_key` cookie is under our control: https://github.com/dwyl/auth_plug/issues/28
and the other two are because we are sourcing the two icons from the dwyl.com website which is fronted by CloudFlare https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies 
We can easily overcome this by hosting the icons ourself in the phoenix assets instead of getting them from the dwyl website.

**Comment by Anutrix** [comment]
The issue is tracked at https://community.cloudflare.com/t/google-chrome-warning-about-cloudflare-cookie/123192/93.

**Comment by nelsonic** [comment]
Closing as no longer seeing this in the latest iteration with **`auth_plug`** #104 ✅ 

Thanks @Anutrix 👌
