### ISSUE TITLE
Ecto custom type for atom

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#93]
My changes on the [statuses]() dependency have converted the `text` value from string to atom.
To make it easier to insert/udpate statuses in Ecto we can define a custom type for atoms

ref: https://hexdocs.pm/ecto/Ecto.Type.html#full-list
linked to #89

**Comment by nelsonic** [comment]
I feel like this is a patch to something that should probably just be a **`String`** ... 
Like we're adding a whole new file [**`/lib/app/ecto_atom.ex`**](https://github.com/dwyl/app-mvp-phoenix/blob/017119d0a18dcbc9b29674628955eb070469daaf/lib/app/ecto_atom.ex) just hide the fact that the data type was changed ... 
**`Postgres`** doesn't know [or _care_] what an `Elixir Atom` is.
In a **`Phoenix`** App, **`Postgres`** is the single-source-of-truth for the **`Data`** not `Ecto` or `Elixir`.
If we are having to hide the data type of a field with its' own custom Ecto Type in an ***MVP***, 
we are _creating_ complexity almost by _definition_. 
I'm using **`fields`** as a demonstration of best practice with data privacy.
This is just adding complexity without _any_ benefit.

Thank you for drawing my attention to this. 👍  >> https://github.com/dwyl/app-mvp-phoenix/issues/94#issuecomment-1183785290
