### ISSUE TITLE
mix setup fail

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#95]
Running `mix setup` fails:
![image](https://user-images.githubusercontent.com/6057298/178230237-8a9bdc33-1ce1-4e10-b45f-c91dd49ff76f.png)

I think this might be linked to the following commit change: https://github.com/dwyl/app-mvp-phoenix/pull/90/commits/0fd80f1290c560f99403113488f020a51d1b40e7

I'm going to look how to fix the setup command

**Comment by SimonLab** [comment]
I think there is a conflict when the trying to installing tailwind again while the _build is currently using the tailwind already installed.
Deleting the build folder and running the setup after works: `rm -rf _build` then `mix setup`.
This is not ideal, however I'm not sure there is another solution and the error might be specific to my case.
We can add a line on the Readme to explain this case

**Comment by nelsonic** [comment]
@SimonLab Yeah, I suspect that there is a DB conflict.

**Comment by nelsonic** [comment]
PR #96 merged. ✅
